const dotenv = require('dotenv');

dotenv.config();

const { connectToDatabase } = require('../src/config/db');
const { Title } = require('../src/models/Title');

const titles = [
  {
    slug: 'matrix',
    title: 'Matrix',
    originalTitle: 'The Matrix',
    type: 'movie',
    year: 1999,
    genres: ['Ação', 'Ficção científica'],
    synopsis: 'Um hacker descobre que a realidade é uma simulação controlada por máquinas.',
    providers: [{ name: 'Prime Video', type: 'subscription' }, { name: 'HBO Max', type: 'subscription' }],
  },
  {
    slug: 'interstellar',
    title: 'Interestelar',
    originalTitle: 'Interstellar',
    type: 'movie',
    year: 2014,
    genres: ['Ficção científica', 'Drama'],
    synopsis: 'Exploradores viajam por um buraco de minhoca para salvar a humanidade.',
    providers: [{ name: 'Paramount+', type: 'subscription' }],
  },
  {
    slug: 'cidade-de-deus',
    title: 'Cidade de Deus',
    type: 'movie',
    year: 2002,
    genres: ['Drama', 'Crime'],
    synopsis: 'A violência e o crime na Cidade de Deus, no Rio de Janeiro, entre os anos 60 e 80.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'tropa-de-elite',
    title: 'Tropa de Elite',
    type: 'movie',
    year: 2007,
    genres: ['Ação', 'Crime', 'Drama'],
    synopsis: 'Capitão Nascimento prepara novos recrutas para combater o tráfico no Rio.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'vingadores-ultimato',
    title: 'Vingadores: Ultimato',
    originalTitle: 'Avengers: Endgame',
    type: 'movie',
    year: 2019,
    genres: ['Ação', 'Aventura', 'Ficção científica'],
    synopsis: 'Os Vingadores se reúnem mais uma vez para reverter os estragos causados por Thanos.',
    providers: [{ name: 'Disney+', type: 'subscription' }],
  },
  {
    slug: 'oppenheimer',
    title: 'Oppenheimer',
    type: 'movie',
    year: 2023,
    genres: ['Drama', 'Biografia', 'História'],
    synopsis: 'A história do físico J. Robert Oppenheimer e o desenvolvimento da bomba atômica.',
    providers: [{ name: 'Prime Video', type: 'rent' }, { name: 'Apple TV', type: 'rent' }],
  },
  {
    slug: 'duna',
    title: 'Duna',
    originalTitle: 'Dune',
    type: 'movie',
    year: 2021,
    genres: ['Ficção científica', 'Aventura'],
    synopsis: 'Paul Atreides viaja ao planeta Arrakis para garantir o futuro de sua família.',
    providers: [{ name: 'HBO Max', type: 'subscription' }],
  },
  {
    slug: 'o-poderoso-chefao',
    title: 'O Poderoso Chefão',
    originalTitle: 'The Godfather',
    type: 'movie',
    year: 1972,
    genres: ['Crime', 'Drama'],
    synopsis: 'A saga da família Corleone no submundo do crime organizado.',
    providers: [{ name: 'Paramount+', type: 'subscription' }],
  },
  {
    slug: 'jurassic-park',
    title: 'Jurassic Park',
    type: 'movie',
    year: 1993,
    genres: ['Aventura', 'Ficção científica'],
    synopsis: 'Um parque temático com dinossauros clonados sai do controle.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'pantera-negra',
    title: 'Pantera Negra',
    originalTitle: 'Black Panther',
    type: 'movie',
    year: 2018,
    genres: ['Ação', 'Aventura', 'Ficção científica'],
    synopsis: 'T\'Challa retorna a Wakanda para assumir o trono e proteger seu povo.',
    providers: [{ name: 'Disney+', type: 'subscription' }],
  },
  {
    slug: 'batman-cavaleiro-das-trevas',
    title: 'Batman: O Cavaleiro das Trevas',
    originalTitle: 'The Dark Knight',
    type: 'movie',
    year: 2008,
    genres: ['Ação', 'Crime', 'Drama'],
    synopsis: 'Batman enfrenta o Coringa, criminoso que semeia o caos em Gotham.',
    providers: [{ name: 'HBO Max', type: 'subscription' }],
  },
  {
    slug: 'clube-da-luta',
    title: 'Clube da Luta',
    originalTitle: 'Fight Club',
    type: 'movie',
    year: 1999,
    genres: ['Drama', 'Thriller'],
    synopsis: 'Um homem insone forma um clube de luta clandestino que evolui para algo maior.',
    providers: [{ name: 'Star+', type: 'subscription' }],
  },
  {
    slug: 'parasita',
    title: 'Parasita',
    originalTitle: 'Parasite',
    type: 'movie',
    year: 2019,
    genres: ['Drama', 'Thriller'],
    synopsis: 'Uma família pobre infiltra-se na casa de uma família rica com consequências inesperadas.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'karate-kid',
    title: 'Karate Kid',
    originalTitle: 'The Karate Kid',
    type: 'movie',
    year: 1984,
    genres: ['Drama', 'Ação', 'Família'],
    synopsis: 'Um adolescente aprende artes marciais com um mestre para se defender de valentões.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'top-gun-maverick',
    title: 'Top Gun: Maverick',
    type: 'movie',
    year: 2022,
    genres: ['Ação', 'Drama'],
    synopsis: 'Pete Maverick Mitchell retorna para treinar pilotos em uma missão perigosa.',
    providers: [{ name: 'Paramount+', type: 'subscription' }],
  },
  {
    slug: 'breaking-bad',
    title: 'Breaking Bad',
    type: 'series',
    year: 2008,
    genres: ['Drama', 'Crime', 'Thriller'],
    synopsis: 'Um professor de química passa a fabricar metanfetamina após descobrir que tem câncer.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'stranger-things',
    title: 'Stranger Things',
    type: 'series',
    year: 2016,
    genres: ['Ficção científica', 'Horror', 'Drama'],
    synopsis: 'Amigos em uma cidade pequena enfrentam forças sobrenaturais e experimentos secretos.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'la-casa-de-papel',
    title: 'La Casa de Papel',
    originalTitle: 'Money Heist',
    type: 'series',
    year: 2017,
    genres: ['Crime', 'Drama', 'Thriller'],
    synopsis: 'Um grupo liderado por um mentor executa assaltos elaborados à Casa da Moeda.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'round-6',
    title: 'Round 6',
    originalTitle: 'Squid Game',
    type: 'series',
    year: 2021,
    genres: ['Drama', 'Thriller', 'Ação'],
    synopsis: 'Centenas de participantes competem em jogos mortais por um prêmio milionário.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'game-of-thrones',
    title: 'Game of Thrones',
    type: 'series',
    year: 2011,
    genres: ['Fantasia', 'Drama', 'Aventura'],
    synopsis: 'Nobres famílias disputam o controle do Trono de Ferro em Westeros.',
    providers: [{ name: 'HBO Max', type: 'subscription' }],
  },
  {
    slug: 'the-office',
    title: 'The Office',
    type: 'series',
    year: 2005,
    genres: ['Comédia'],
    synopsis: 'O dia a dia caótico e engraçado dos funcionários de um escritório de papel.',
    providers: [{ name: 'Star+', type: 'subscription' }],
  },
  {
    slug: 'loki',
    title: 'Loki',
    type: 'series',
    year: 2021,
    genres: ['Ação', 'Aventura', 'Ficção científica'],
    synopsis: 'Loki é capturado pela AVT após criar uma nova linha temporal.',
    providers: [{ name: 'Disney+', type: 'subscription' }],
  },
  {
    slug: 'narcos',
    title: 'Narcos',
    type: 'series',
    year: 2015,
    genres: ['Crime', 'Drama', 'Biografia'],
    synopsis: 'A ascensão e queda do cartel de Pablo Escobar vistos pelos olhos dos agentes da DEA.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'dark',
    title: 'Dark',
    type: 'series',
    year: 2017,
    genres: ['Ficção científica', 'Mistério', 'Drama'],
    synopsis: 'Desaparecimentos em uma cidade alemã revelam conexões entre famílias e viagens no tempo.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'the-mandalorian',
    title: 'The Mandalorian',
    type: 'series',
    year: 2019,
    genres: ['Ação', 'Aventura', 'Ficção científica'],
    synopsis: 'Um caçador de recompensas solitário navega pelos territórios da galáxia.',
    providers: [{ name: 'Disney+', type: 'subscription' }],
  },
  {
    slug: 'bridgerton',
    title: 'Bridgerton',
    type: 'series',
    year: 2020,
    genres: ['Drama', 'Romance'],
    synopsis: 'Famílias da alta sociedade londrina competem na temporada de casamentos.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'the-boys',
    title: 'The Boys',
    type: 'series',
    year: 2019,
    genres: ['Ação', 'Comédia', 'Crime'],
    synopsis: 'Um grupo de vigilantes combate super-heróis corruptos abusados pelo poder.',
    providers: [{ name: 'Prime Video', type: 'subscription' }],
  },
  {
    slug: 'chernobyl',
    title: 'Chernobyl',
    type: 'series',
    year: 2019,
    genres: ['Drama', 'História', 'Thriller'],
    synopsis: 'A história do desastre nuclear de Chernobyl e suas consequências.',
    providers: [{ name: 'HBO Max', type: 'subscription' }],
  },
  {
    slug: 'peaky-blinders',
    title: 'Peaky Blinders',
    type: 'series',
    year: 2013,
    genres: ['Crime', 'Drama'],
    synopsis: 'Uma gangue em Birmingham expande seus negócios após a Primeira Guerra Mundial.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
  {
    slug: 'wednesday',
    title: 'Wednesday',
    type: 'series',
    year: 2022,
    genres: ['Comédia', 'Fantasia', 'Mistério'],
    synopsis: 'Wednesday Addams investiga uma série de assassinatos na Academia Nevermore.',
    providers: [{ name: 'Netflix', type: 'subscription' }],
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) throw new Error('Missing MONGODB_URI');

  await connectToDatabase(uri);

  await Title.deleteMany({});
  const inserted = await Title.insertMany(titles);

  console.log(`Seed concluído: ${inserted.length} títulos inseridos.`);
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
